"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 30

[character] # The name of the module we are configuring is 'character'

[package]
disabled = true

[rust]

[status]
disabled = false

[time]
disabled = false

[custom.rust_custom]
detect_files = ['Cargo.toml'] # can specify filters but wildcards are not supported
